# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2020-07-23 11:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("example", "0002_migrate_anonymised"),
    ]

    operations = [
        migrations.RemoveField(model_name="healthrecord", name="anonymised"),
        migrations.RemoveField(model_name="mailinglistlog", name="anonymised"),
        migrations.RemoveField(model_name="person", name="anonymised"),
        migrations.RemoveField(model_name="personprofile", name="anonymised"),
    ]
