# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-08-21 15:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PersonalData",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                )
            ],
            options={"verbose_name_plural": "Personal data", "managed": False},
        ),
        migrations.CreateModel(
            name="EventLog",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event",
                    models.CharField(
                        choices=[("delete", "Delete"), ("anonymise", "Anonymise")],
                        max_length=9,
                    ),
                ),
                ("app_label", models.CharField(max_length=255)),
                ("model_name", models.CharField(max_length=255)),
                ("target_pk", models.TextField()),
            ],
        ),
    ]
