# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-24 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventlog',
            name='acting_user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
