# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 11:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anonymised', models.BooleanField(default=False)),
                ('description', models.CharField(default='', max_length=255)),
                ('start_date', models.DateTimeField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_length', models.DurationField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='eventlog',
            name='acting_user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='error_message',
            field=models.CharField(blank=True, default=None, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='eventlog',
            name='event',
            field=models.CharField(choices=[('delete', 'Delete'), ('anonymise', 'Anonymise'), ('anonymisation recursion start', 'Anonymisation Recursion Start'), ('anonymisation recursion end', 'Anonymisation Recursion End'), ('anonymisation abandoned, already done', 'Anonymisation Skipped, Already Done')], max_length=37),
        ),
    ]
