# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-28 16:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_length', models.DurationField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='eventlog',
            name='acting_user',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='eventlog',
            name='log_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
