# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-02-05 16:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0002_privacyanonymised'),
    ]

    operations = [
        migrations.AlterField(
            model_name='privacyanonymised',
            name='object_id',
            field=models.CharField(max_length=36),
        ),
    ]
