# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-06-25 18:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0002_auto_20200624_1702'),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionPolicyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('policy_length', models.DurationField(blank=True, null=True)),
            ],
        ),
    ]
