# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0004_eventlog_error_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event',
            field=models.CharField(choices=[('delete', 'Delete'), ('anonymise', 'Anonymise'), ('anonymise', 'Anonymisation Recursion Start'), ('anonymise', 'Anonymisation Recursion End')], max_length=9),
        ),
    ]
