# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-05 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0005_auto_20200705_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event',
            field=models.CharField(choices=[('delete', 'Delete'), ('anonymise', 'Anonymise'), ('anonymisation recursion start', 'Anonymisation Recursion Start'), ('anonymisation recursion end', 'Anonymisation Recursion End')], max_length=29),
        ),
    ]
