# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-06 17:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0006_auto_20200705_1229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='retentionpolicyitem',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
