# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-08 12:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0008_auto_20200706_1805'),
    ]

    operations = [
        migrations.AddField(
            model_name='retentionpolicyitem',
            name='anonymised',
            field=models.BooleanField(default=False),
        ),
    ]
