# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-07-16 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gdpr_assist', '0010_auto_20200708_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventlog',
            name='event',
            field=models.CharField(choices=[('delete', 'Delete'), ('anonymise', 'Anonymise'), ('anonymisation recursion start', 'Anonymisation Recursion Start'), ('anonymisation recursion end', 'Anonymisation Recursion End'), ('anonymisation abandoned, already done', 'Anonymisation Skipped, Already Done')], max_length=37),
        ),
    ]
